import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { sideBySideMarkdown, table } from './present';
import { RECORDING, honxSpinOff, loadRecorded, strcxImplausibleCash, summarize, type RecordedTransition } from './recorded';
import { REPO_ROOT } from './runner';

/**
 * Generates docs/findings/what-this-catches.md: the leave-behind for issuer and buyer conversations.
 * Every figure is computed from the recorded issuer data set by the production classifier.
 * No network access, no live issuer feed, no market prices.
 */

const OUTPUT = join(REPO_ROOT, 'docs/findings/what-this-catches.md');
const day = (r: RecordedTransition) => r.transition.activatedAt.toISOString().slice(0, 10);
const byCount = (tally: Record<string, number>) => Object.entries(tally).toSorted((a, b) => b[1] - a[1]);
const shortIds = (text: string) => text.replace(/\b([0-9a-f]{8})-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/g, '$1…');

async function main() {
  const rows = await loadRecorded();
  const s = summarize(rows);
  const honx = honxSpinOff(rows);
  const strcx = strcxImplausibleCash(rows);
  const mislabels = s.labelMismatches;
  const increases = s.increasesNotCashDividends;

  const doc = `# What Corpact catches

Corpact turns tokenized-stock multiplier changes into an evidence-backed income ledger. This page shows what that means on **real recorded issuer data**: every multiplier change xStocks published for its Solana assets, recorded 2026-09-13, run through the production classifier.

> **Source and limits.** Recorded issuer responses (\`${RECORDING}\`), replayed offline, with no live calls to the issuer. There are no market prices on this page: USD figures are the issuer's own per-share cash amounts, or prices implied by them. Generated by \`pnpm --filter @corpact/demo catches\`, and pinned by \`apps/demo/src/recorded.test.ts\`.

## ${s.transitions} multiplier changes, every one accounted for

| Outcome | Count |
|---|---|
| Verified cash dividend (issuer action matched on exact multipliers and activation time) | **${s.dividends.total}** |
| Split, reconciled to the issuer's unit ratio | **${s.splits.total}** |
| Not attributed: shown as pending classification, **no income booked** | **${s.unclassified.total}** |

**How dividends are valued**

${table(['Valuation outcome', 'Dividends'], byCount(s.dividends.byOutcome))}

**Why ${s.unclassified.total} changes are not income**

${table(['Stated reason', 'Changes'], byCount(s.unclassified.byReason))}

**Splits by issuer type:** ${byCount(s.splits.byIssuerType).map(([t, n]) => `${t} ${n}`).join(', ')}.

## Case 1 — ${honx.title}

${sideBySideMarkdown(honx)}

## Case 2 — ${strcx.title}

${sideBySideMarkdown(strcx)}

Implied reinvestment price, from the issuer's own numbers (M_old × net cash ÷ (M_new − M_old)): **$${Number(strcx.impliedPriceUsd).toLocaleString('en-US', { maximumFractionDigits: 2 })}** per share, against a median of **$${strcx.peerMedianUsd}** across STRCx's other dividends.

## Case 3 — The label is not evidence

The multiplier-history \`reason\` field is the obvious thing to trust. On ${mislabels.length} of the ${s.transitions} changes, issuer corporate-action evidence contradicts it:

${table(
  ['Asset', 'Activation', 'Label says', 'Issuer evidence', 'Corpact'],
  mislabels.map((r) => [
    r.symbol,
    day(r),
    r.historyReason,
    r.action?.type ?? 'no matching action',
    r.classification.kind === 'unclassified' ? 'Not income — pending classification' : r.classification.kind,
  ]),
)}

More broadly, "any multiplier increase is income" is wrong **${increases.length} times**. ${increases.filter((r) => r.action !== null).length} are splits, spin-offs or stock dividends the issuer published. ${increases.filter((r) => r.action === null).length} are changes the issuer never explained:

${table(
  ['Asset', 'Activation', 'Change', 'Corpact'],
  increases.map((r) => [
    r.symbol,
    day(r),
    `+${((r.transition.after / r.transition.before - 1) * 100).toFixed(2)}%`,
    r.classification.kind === 'split'
      ? `Split (${r.action?.type ?? 'issuer ratio'})`
      : r.classification.kind === 'unclassified'
        ? shortIds(r.classification.reasons[0]!)
        : r.classification.kind,
  ]),
)}

## Also handled

- **Income with no account write.** A multiplier activates at a scheduled time with no transaction, so nothing appears in a transfer feed. The dividend is detected from chain time.
- **Corrections.** Issuers revise actions (STRCx event c5721924 went through several revisions). A changed interpretation is journaled as a reversal plus a replacement, and settled entries are never edited.
- **Endpoint disagreement.** The issuer's own endpoints differ in the last representable digit (HONx 2026-05-15: \`1.020191445467247\` vs \`"1.0201914454672472"\`). The chain f64 is canonical, and matches allow a 4ε tolerance.
- **Late publication.** A write published after its scheduled time (VTIx: 70 s) is recognized, not reported as missing history.
- **Partial history.** A position whose history cannot be fully replayed is marked partial, and **no yield is claimed for it**.

## Open, not smoothed over

- **Price sources disagree.** On 2026-09-13, CRWDx was quoted at $206.37 by xStocks and $119.41 by Jupiter, a 42% gap. There is no rule yet for staleness or disagreement between price sources, so Corpact publishes **no market-price valuations**. A dividend without trustworthy issuer cash keeps its quantity, with USD **unknown**, never zero.
- **Non-cash distributions.** Spin-offs, stock dividends and mergers are real economic events. Today they are shown as pending classification, not income. That is deliberately conservative, not a final accounting policy.
`;

  writeFileSync(OUTPUT, doc);
  console.log(`Wrote ${OUTPUT}: ${s.transitions} changes, ${mislabels.length} label mismatches, ${increases.length} non-dividend increases`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? `${error.name}: ${error.message}` : error);
  process.exitCode = 1;
});
