import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Synthetic issuer records in the recorded xStocks response shapes, so the demo runs the
 * same fixture adapter, Zod schemas and classifier as production. Nothing here is issuer data.
 */

export interface DemoAsset {
  symbol: string;
  name: string;
  underlyingSymbol: string;
  mint: string;
}

export type DemoActionType = 'CashDividend' | 'ForwardSplit' | 'SpinOff';

export interface DemoCorporateAction {
  eventId: string;
  version: number;
  symbol: string;
  type: DemoActionType;
  status: 'Initial' | 'Corrected';
  effectiveUnix: bigint;
  createdUnix: bigint;
  multiplierOld: string;
  multiplierNew: string;
  grossCashUsd: string | null;
  netCashUsd: string | null;
  withholdingTaxRate: string | null;
  fromUnits: string | null;
  toUnits: string | null;
  notes: string | null;
}

export interface DemoMultiplierHistory {
  id: string;
  symbol: string;
  /** The issuer's free-text label. Phase 0 showed it is not evidence; the demo includes a mislabelled one. */
  reason: string;
  multiplier: number;
  previousMultiplier: number;
  activationUnix: bigint;
}

const iso = (unix: bigint) => new Date(Number(unix) * 1000).toISOString();

export function writeIssuerFixtures(
  dir: string,
  runId: string,
  input: { assets: readonly DemoAsset[]; actions: readonly DemoCorporateAction[]; history: readonly DemoMultiplierHistory[] },
): void {
  mkdirSync(dir, { recursive: true });
  const source = `SYNTHETIC demo run ${runId}: generated by apps/demo against a local validator. Not issuer data.`;
  const write = (file: string, body: unknown) => writeFileSync(join(dir, file), `${JSON.stringify(body, null, 2)}\n`);

  write('assets.json', {
    _source: source,
    nodes: input.assets.map((a) => ({
      symbol: a.symbol,
      name: a.name,
      underlyingSymbol: a.underlyingSymbol,
      isTradingHalted: false,
      deployments: [{ address: a.mint, network: 'Solana' }],
    })),
  });

  const bySymbol: Record<string, unknown[]> = {};
  for (const h of input.history.toSorted((a, b) => (a.activationUnix > b.activationUnix ? -1 : 1))) {
    (bySymbol[h.symbol] ??= []).push({
      id: h.id,
      reason: h.reason,
      multiplier: h.multiplier,
      previousMultiplier: h.previousMultiplier,
      activationDateTime: iso(h.activationUnix),
    });
  }
  write('multiplier-history.json', { _source: source, bySymbol });

  write('corporate-actions-history.json', {
    _source: source,
    nodes: input.actions.map((a) => ({
      eventId: a.eventId,
      version: a.version,
      xstockSymbol: a.symbol,
      caType: a.type,
      status: a.status,
      effectiveTimeUtc: iso(a.effectiveUnix),
      createdTimeUtc: iso(a.createdUnix),
      multiplierOld: a.multiplierOld,
      multiplierNew: a.multiplierNew,
      grossCashflowUsd: a.grossCashUsd,
      netCashflowUsd: a.netCashUsd,
      withholdingTaxRate: a.withholdingTaxRate,
      fromUnits: a.fromUnits,
      toUnits: a.toUnits,
      notes: a.notes,
    })),
  });
  write('corporate-actions-upcoming.json', { _source: source, nodes: [] });
}
