// Generated by `pnpm --filter @corpact/demo action-docs` from ACTION_KIND_SPECS. Do not edit.
import type { NavItem } from './nav';

export const ACTION_NAV: NavItem[] = [
  { title: 'All action types', slug: 'actions' },
  { title: 'Cash dividend', slug: 'actions/cash-dividend' },
  { title: 'Withholding refund', slug: 'actions/withholding-adjustment' },
  { title: 'Stock dividend', slug: 'actions/stock-dividend' },
  { title: 'Cash and stock dividend', slug: 'actions/cash-and-stock-dividend' },
  { title: 'Forward split', slug: 'actions/forward-split' },
  { title: 'Reverse split', slug: 'actions/reverse-split' },
  { title: 'Unit split', slug: 'actions/unit-split' },
  { title: 'Fractional cash in lieu', slug: 'actions/cash-in-lieu' },
  { title: 'Spin-off', slug: 'actions/spin-off' },
  { title: 'Rights distribution', slug: 'actions/rights-distribution' },
  { title: 'Stock-for-stock merger', slug: 'actions/stock-merger' },
  { title: 'Cash merger', slug: 'actions/cash-merger' },
  { title: 'Stock and cash merger', slug: 'actions/mixed-merger' },
  { title: 'Identity change', slug: 'actions/identity-change' },
  { title: 'Redemption or wrapper discontinuation', slug: 'actions/redemption' },
  { title: 'Delisting or worthless removal', slug: 'actions/delisting' },
  { title: 'Permanent-delegate transfer', slug: 'actions/seizure' },
  { title: 'Unknown', slug: 'actions/unknown' },
];
