// Generated by `pnpm --filter @corpact/demo action-docs` from ACTION_KIND_SPECS. Do not edit.
import type { NavItem } from './nav';

export const ACTION_NAV: NavItem[] = [
  { title: 'All action types', slug: 'actions' },
  { title: 'Cash dividend', slug: 'actions/cash-dividend' },
  { title: 'Withholding refund', slug: 'actions/withholding-adjustment' },
  { title: 'Stock dividend', slug: 'actions/stock-dividend' },
  { title: 'Forward split', slug: 'actions/forward-split' },
  { title: 'Reverse split', slug: 'actions/reverse-split' },
  { title: 'Spin-off', slug: 'actions/spin-off' },
  { title: 'Rights distribution', slug: 'actions/rights-distribution' },
  { title: 'Identity change', slug: 'actions/identity-change' },
];
